In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import OneHotEncoder

In [4]:
line = np.random.randint(0,10,100)

In [5]:
line

array([9, 5, 6, 9, 7, 6, 1, 3, 1, 9, 8, 6, 8, 8, 8, 8, 6, 5, 5, 8, 2, 1,
       8, 2, 7, 3, 5, 0, 8, 9, 6, 2, 2, 5, 6, 9, 8, 2, 4, 4, 9, 7, 8, 6,
       2, 5, 2, 0, 3, 9, 5, 1, 7, 7, 8, 7, 2, 3, 2, 9, 2, 6, 0, 4, 4, 2,
       7, 2, 2, 6, 6, 6, 4, 0, 8, 0, 9, 9, 9, 0, 7, 4, 2, 4, 1, 4, 9, 1,
       1, 7, 0, 5, 2, 0, 3, 8, 9, 7, 8, 7])

In [3]:
one = OneHotEncoder(categories="auto")

In [7]:
one.fit(line.reshape(-1,1))#we need rows rather tha columns as column represents feature

OneHotEncoder(categorical_features=None, categories='auto',
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [9]:
one.categories_

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [12]:
line[:4]

array([9, 5, 6, 9])

In [13]:
one.transform(line.reshape(-1,1)).todense()#as it returns sparx matrix so we need it to convert it to dense matrix

matrix([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],


In [14]:
line

array([9, 5, 6, 9, 7, 6, 1, 3, 1, 9, 8, 6, 8, 8, 8, 8, 6, 5, 5, 8, 2, 1,
       8, 2, 7, 3, 5, 0, 8, 9, 6, 2, 2, 5, 6, 9, 8, 2, 4, 4, 9, 7, 8, 6,
       2, 5, 2, 0, 3, 9, 5, 1, 7, 7, 8, 7, 2, 3, 2, 9, 2, 6, 0, 4, 4, 2,
       7, 2, 2, 6, 6, 6, 4, 0, 8, 0, 9, 9, 9, 0, 7, 4, 2, 4, 1, 4, 9, 1,
       1, 7, 0, 5, 2, 0, 3, 8, 9, 7, 8, 7])