In [0]:
from keras.models import Sequential 
from keras.layers import Dense
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import pandas as pd


In [0]:
data = pd.read_csv("sample_data/mnist_train_small.csv")

In [0]:
X = data.values[:,1:]
y = data.values[:,0]

In [12]:
y

array([5, 7, 9, ..., 2, 9, 5])

In [13]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [0]:
ohe = OneHotEncoder(categories="auto")
y_hot = ohe.fit_transform(y.reshape(-1,1)).todense()

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y_hot, test_size=0.33, random_state=42)

In [109]:
model = Sequential()
layer_1 = Dense(400,activation="tanh",input_shape=[784])
layer_2 = Dense(100,activation="tanh")
layer_3 = Dense(50,activation="tanh")
layer_4 = Dense(10,activation="softmax")
model.add(layer_1)
model.add(layer_2)
model.add(layer_3)
model.add(layer_4)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_80 (Dense)             (None, 400)               314000    
_________________________________________________________________
dense_81 (Dense)             (None, 100)               40100     
_________________________________________________________________
dense_82 (Dense)             (None, 50)                5050      
_________________________________________________________________
dense_83 (Dense)             (None, 10)                510       
Total params: 359,660
Trainable params: 359,660
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [111]:
model.fit(X_train,y_train,epochs=10,batch_size=30)

Epoch 1/10
13399/13399 [==============================] - 6s 467us/step - loss: 0.6341 - acc: 0.8055
Epoch 2/10
13399/13399 [==============================] - 4s 311us/step - loss: 0.4744 - acc: 0.8486
Epoch 3/10
13399/13399 [==============================] - 4s 301us/step - loss: 0.4527 - acc: 0.8550
Epoch 4/10
13399/13399 [==============================] - 4s 303us/step - loss: 0.4395 - acc: 0.8590
Epoch 5/10
13399/13399 [==============================] - 4s 321us/step - loss: 0.4244 - acc: 0.8643
Epoch 6/10
13399/13399 [==============================] - 5s 339us/step - loss: 0.3901 - acc: 0.8776
Epoch 7/10
13399/13399 [==============================] - 5s 342us/step - loss: 0.3701 - acc: 0.8846
Epoch 8/10
13399/13399 [==============================] - 5s 339us/step - loss: 0.3483 - acc: 0.8907
Epoch 9/10
13399/13399 [==============================] - 5s 340us/step - loss: 0.3351 - acc: 0.8920
Epoch 10/10
13399/13399 [==============================] - 5s 348us/step - loss: 0.3469 - a

In [112]:
model.evaluate(X_test,y_test)

6600/6600 [==============================] - 1s 191us/step


[0.33358460731578593, 0.8983333333333333]

In [116]:
model.predict(X_test[:1])

array([[2.49374949e-04, 1.33250847e-01, 5.69418399e-03, 2.11753733e-02,
        1.75219087e-03, 2.70006317e-03, 1.10359215e-05, 5.22391200e-01,
        2.03444257e-01, 1.09331459e-01]], dtype=float32)

In [118]:
import numpy as np
np.argmax(model.predict(X_test[:1]),axis=1)

array([7])

In [119]:
! wget https://github.com/coding-blocks-archives/ML-Noida-2019-June-One/blob/logo/datasets/nums/eight.jpeg

--2019-07-04 13:27:40--  https://github.com/coding-blocks-archives/ML-Noida-2019-June-One/blob/logo/datasets/nums/eight.jpeg
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘eight.jpeg’

eight.jpeg              [ <=>                ]  65.46K  --.-KB/s    in 0.03s   

2019-07-04 13:27:45 (2.52 MB/s) - ‘eight.jpeg’ saved [67033]



In [0]:
import cv2

In [0]:
eight = cv2.imread("eight.jpeg")

In [129]:
gray = cv2.cvtColor(eight,cv2.COLOR_BGR2GRAY)

error: ignored

In [130]:
small = cv2.resize(gray,(28,28))

NameError: ignored

In [134]:
small = (small<100).astype(int) * 255 

NameError: ignored

In [132]:
model.predict(np.array([small.flatten]))

NameError: ignored

In [0]:
np.argmax(model.predict(np.array([small.flatten])))