In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_regression

In [2]:
bias = 100

X,y,coff = make_regression(100,n_features=5,noise=4,bias=bias,random_state=42,coef=True)

In [3]:
X

array([[ 0.97511973, -0.67716171, -0.01224677, -0.89725437,  0.07580456],
       [ 0.08187414, -0.48536355,  0.75896922, -0.77282521, -0.23681861],
       [-1.4123037 , -0.90802408, -0.56228753, -1.01283112,  0.31424733],
       [-0.64511975,  0.36163603,  1.35624003, -0.07201012,  1.0035329 ],
       [-0.62269952,  0.28099187, -1.9520878 , -0.1517851 ,  0.58831721],
       [-0.45006547,  0.04698059, -1.59442766, -0.59937502,  0.0052437 ],
       [ 0.77463405,  0.44381943, -0.48423407,  1.26691115, -0.70766947],
       [ 0.35701549,  0.8496021 , -0.20812225, -0.49300093, -0.58936476],
       [-1.3044695 , -0.08912004,  0.38406545, -0.03269475, -2.0674421 ],
       [ 0.17318093, -1.24573878, -0.44651495,  0.85639879,  0.21409374],
       [ 0.29698467,  0.52194157,  0.78182287, -1.23695071, -1.32045661],
       [-1.72491783, -1.91328024, -0.46341769, -0.46572975,  0.24196227],
       [-1.98756891,  0.09176078,  0.8219025 ,  0.08704707, -0.29900735],
       [-0.0555477 , -1.70338244,  0.0

In [4]:
y

array([  36.64125728,   49.4262697 , -160.57481268,  216.91770285,
        -22.36067643,  -55.77656873,  208.89730598,  141.79134351,
        -39.88304438,   19.68617343,  105.5476569 , -242.97122653,
         33.92910308,  -21.19928635,  100.54563512,  221.47267553,
         88.65466701, -158.00102476,  148.40321925,   65.41758501,
        187.48324326,  111.75836886,   72.46097609,  253.24261157,
        260.78040557,  381.05151313,  107.52086759,  257.82545233,
       -100.19627363,  407.41124392,  -19.64056463,  144.40701964,
         88.79765857,  135.23744706,  266.35433677,   24.66731191,
        230.16318409,   60.83016037,  227.17274346,  164.81644614,
        -44.88515274,  111.2073444 ,  108.54668938,  187.94141477,
        503.35801496,  277.1956793 ,  455.00942069,   47.51590985,
         43.05667039,  295.0553807 ,  133.14961673,   -5.30795995,
         99.0380462 , -196.3213438 , -165.43445128, -123.148049  ,
        152.36377655,  202.61611576,  -40.20983294,  171.36893

In [5]:
coff

array([60.57748194, 98.65152488, 64.59172413, 57.07783047, 35.60967259])

In [6]:
expected_theta = np.hstack([[bias],coff])

In [7]:
expected_theta


array([100.        ,  60.57748194,  98.65152488,  64.59172413,
        57.07783047,  35.60967259])

In [11]:
X_update = np.hstack([np.ones((X.shape[0],1)),X])

In [12]:
X_update

array([[ 1.        ,  0.97511973, -0.67716171, -0.01224677, -0.89725437,
         0.07580456],
       [ 1.        ,  0.08187414, -0.48536355,  0.75896922, -0.77282521,
        -0.23681861],
       [ 1.        , -1.4123037 , -0.90802408, -0.56228753, -1.01283112,
         0.31424733],
       [ 1.        , -0.64511975,  0.36163603,  1.35624003, -0.07201012,
         1.0035329 ],
       [ 1.        , -0.62269952,  0.28099187, -1.9520878 , -0.1517851 ,
         0.58831721],
       [ 1.        , -0.45006547,  0.04698059, -1.59442766, -0.59937502,
         0.0052437 ],
       [ 1.        ,  0.77463405,  0.44381943, -0.48423407,  1.26691115,
        -0.70766947],
       [ 1.        ,  0.35701549,  0.8496021 , -0.20812225, -0.49300093,
        -0.58936476],
       [ 1.        , -1.3044695 , -0.08912004,  0.38406545, -0.03269475,
        -2.0674421 ],
       [ 1.        ,  0.17318093, -1.24573878, -0.44651495,  0.85639879,
         0.21409374],
       [ 1.        ,  0.29698467,  0.52194157,  0.

In [13]:
X.shape

(100, 5)

In [14]:
X_update.shape

(100, 6)

In [15]:
class LinearRegression:
    
    def __init__(self, lr = 0.01,itrs=100):
        self.lr = lr #learning rate
        self.itrs = itrs
    
    def fit(self,X,y):
        
        self.X = X
        self.y = y.reshape(-1,1)
        
        first = np.dot(X.T,X)
        second = np.dot(X.T,y)
        
        self.theta = np.dot(np.linalg.pinv(first),second)
        
       
    def predict(self,X):
        return LinearRegression.hypothesis(X,self.theta).flatten()
    
    
    def error(self):   
        yh = LinearRegression.hypothesis(self.X,self.theta)
        return np.sum((yh - self.y) **2)
    
    
    
    @classmethod
    def hypothesis(cls,X,theta):
        return np.dot(X,theta)

In [21]:
model = LinearRegression(itrs=10)

In [22]:
model.fit(X_update,y)

In [23]:
model.theta

array([99.96589883, 61.07849977, 98.76370047, 63.27924913, 56.24314895,
       35.60182776])

In [24]:
expected_theta

array([100.        ,  60.57748194,  98.65152488,  64.59172413,
        57.07783047,  35.60967259])