! python3 -m pip install numpy

! echo "hello"

In [1]:
import numpy as np

In [2]:
oneD = np.array([1,2,3,5])

In [3]:
oneD = np.array(range(5))

In [4]:
oneD


array([0, 1, 2, 3, 4])

In [6]:
twoD = np.array([range(0,5),range(5,10)])

In [7]:
twoD

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
twoD = np.array([range(0,5),range(5,15)])

In [9]:
twoD

array([range(0, 5), range(5, 15)], dtype=object)

In [13]:
a = np.arange(50).reshape(10,-1)

In [14]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [15]:
a.shape

(10, 5)

In [16]:
a.ndim

2

In [18]:
a[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
a[:,1]=0

In [20]:
a

array([[ 0,  0,  2,  3,  4],
       [ 5,  0,  7,  8,  9],
       [10,  0, 12, 13, 14],
       [15,  0, 17, 18, 19],
       [20,  0, 22, 23, 24],
       [25,  0, 27, 28, 29],
       [30,  0, 32, 33, 34],
       [35,  0, 37, 38, 39],
       [40,  0, 42, 43, 44],
       [45,  0, 47, 48, 49]])

In [22]:
a[:,1:3]=0

In [23]:
a

array([[ 0,  0,  0,  3,  4],
       [ 5,  0,  0,  8,  9],
       [10,  0,  0, 13, 14],
       [15,  0,  0, 18, 19],
       [20,  0,  0, 23, 24],
       [25,  0,  0, 28, 29],
       [30,  0,  0, 33, 34],
       [35,  0,  0, 38, 39],
       [40,  0,  0, 43, 44],
       [45,  0,  0, 48, 49]])

In [26]:
one = np.arange(20).reshape(5,-1)

In [27]:
two= np.arange(40,60).reshape(5,-1)

In [28]:
one

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [29]:
two

array([[40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [30]:
np.hstack([one,two])

array([[ 0,  1,  2,  3, 40, 41, 42, 43],
       [ 4,  5,  6,  7, 44, 45, 46, 47],
       [ 8,  9, 10, 11, 48, 49, 50, 51],
       [12, 13, 14, 15, 52, 53, 54, 55],
       [16, 17, 18, 19, 56, 57, 58, 59]])

broadcasting

In [32]:
one *10

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110],
       [120, 130, 140, 150],
       [160, 170, 180, 190]])

In [33]:
one + two


array([[40, 42, 44, 46],
       [48, 50, 52, 54],
       [56, 58, 60, 62],
       [64, 66, 68, 70],
       [72, 74, 76, 78]])

In [34]:
one + np.array(range(3))

ValueError: operands could not be broadcast together with shapes (5,4) (3,) 

In [35]:
one + np.array(range(4))

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])

In [36]:
np.sin(one)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [37]:
np.max(one)

19

In [38]:
np.min(one,axis=0)

array([0, 1, 2, 3])

In [39]:
np.mean(one,axis=0)

array([ 8.,  9., 10., 11.])

In [40]:
np.std(one)

5.766281297335398

In [41]:
np.std(one,axis=0)

array([5.65685425, 5.65685425, 5.65685425, 5.65685425])

In [44]:
data = np.linspace(0,2*np.pi,10)

In [45]:
data

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [46]:
np.sin(data)

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])